## Overview

In this PA, you will will be creating and manipulating basic objects to uncover a top secret message.

### Hint 1

As you work through this PA, you will encounter some code that does not work as you want it to.  Don't despair!  Errors (when R is unable to run your code) and bugs (when the code doesn't do what you hoped) are a natural part of coding.  Even the best of the best deal with these problems regularly - learning to track down the issue is a skill that you can learn and practice.

Google is your friend!  If an error is confusing, copy it into Google and see what other people are saying.  If you don't know how to do something, search for it.

### Hint 2

Just because there is no error message doesn't mean everything went smoothly.  You should be regularly printing out your objects, to see they contain the information and format that you expect.

For example, if you have an object named `my_thing`, you might first want to simply look at the object by typing its name.

However, you might also want to make sure it is the right **object type** and/or the right **object structure**.


In [2]:
type(my_thing)
len(my_thing)

NameError: name 'my_thing' is not defined

## Part One: Setup

Each of the following code chunks will cause an error and/or do the desired task incorrectly.  Find the mistake, and correct it to complete the intended action.




1. Create lists containing the upper case letters, lower case letters, and some punctuation marks.


In [3]:
lower_case = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]

upper_case = ["A", "B", "C", "D", "E", "F", "G", "H" "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

punctuation = [".", ",", "!", "?", "'", '"', "(", ")", " ", "-", ";", ":"]

We can't have a triple " mark.

2. Make one long list containing all the symbols.  Find the length of this list.


In [4]:
all_symbols = [lower_case, upper_case, punctuation]

len(all_symbols)

3

3. Repeat the previous steps, but instead of using *list* type objects, use **numpy arrays**.  Don't forget to **import** the numpy library!


In [5]:
import numpy as np

lower_case = np.array(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"])

upper_case = np.array(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"])

punctuation = np.array([".", ",", "!", "?", "'", "\"" "(", ")", " ", "-", ";", ":"])

## Use np.concatenate to combine into long array
all_symbols = np.concatenate((lower_case, upper_case, punctuation))

4. Make a **pandas data frame**, with one column called "Symbol" containing the `all_symbols` array.


In [6]:
import pandas as pd

symbols_DF = pd.DataFrame(all_symbols)

symbols_DF.rename(columns = {0: "Symbol"})

Symbol
0       a
1       b
2       c
3       d
4       e
..    ...
58      )
59       
60      -
61      ;
62      :

[63 rows x 1 columns]

## Part Two: Decoding the secret message.


In [16]:
top_secret = pd.read_csv("https://www.dropbox.com/s/k72h1zewk4gtqep/PA_Secret_Code?dl=1", header=None)

top_secret = top_secret[0].to_numpy()

### Hint

Recall that basic math operations are **vectorized**.  This means you don't have to repeat the process for each item in a list; you can apply the math to the whole thing at once.

### Instructions

By altering this top secret set of numbers, you will be able to create a message.  Write your own code to complete the steps below.

1. Add 14 to every number.
2. Multiply every number by 18, then subtract 257.
3. Exponentiate every number.  (That is, do e^[number].  You may have to Google how to do this!)
4. Square every number.

**Checkpoint:** Headquarters has informed you that at this stage of decoding, there should be 352 numbers in the secret message that are below 17.  Write code to check if this is true for your data.


5. Turn your one-dimensional array of numbers into a two-dimensional array (matrix) with 5 columns.
6. Separately from your top secret numbers, create an array of all the even numbers between 1 and 382. Name it "evens". That is, "evens" should contain 2, 4, 6, 8 ..., 382.
7. Subtract the "evens" vector from the first column of your secret message matrix.
8. Subtract 100 from all numbers in the 18-24th rows of the 3rd column.
9. Multiply all numbers in the 4th and 5th column by 2.
10. Turn your matrix back into a one dimensional array.


**Checkpoint:** Headquarters has informed you that at this stage of decoding, all numbers in indices 500 and beyond are below 100.  Write code to check if your numbers fulfill this requirement.

11. Take the square root of all numbers in indices 37 to 464.
12. Round all numbers to the nearest whole number.
13. Replace all instances of the number 39 with 20.

**Checkpoint:** Headquarters has informed you that your final message should have 344 even numbers.  Write code to check if your numbers fulfill this requirement.

## Part 3: The secret message!

Run the following to discover the final message!  Google the first line of this message, if you do not recognize it, to see what it is.


In [8]:
''.join(map(str, symbols_DF.loc[top_secret]['Symbol']))

KeyError: "None of [Index([ 0.39104270677516, 0.386445083484116,  0.37131377305518, 0.338811793814894,  0.37131377305518, 0.396957206698566,\n       0.354794131173328, 0.375732236794894, 0.369328801833454, 0.374048219522214,\n       ...\n       0.372714630100372, 0.333747306126176, 0.343093757143428, 0.360289290710268, 0.312576749124872, 0.338811793814894,\n       0.258523689428891, 0.277777777777779, 0.303230298107614, 0.368809575916449],\n      dtype='float64', length=955)] are in the [index]"

In [22]:
import numpy as np

top_secret1 = top_secret+14
top_secret2 = top_secret1*18 - 257

top_secret3 = np.exp(top_secret2)

top_secret4 = top_secret3**2
print(top_secret4)

print(np.sum(top_secret4<17))



[5.900e+01 5.000e+01 2.900e+01 9.000e+00 2.900e+01 7.300e+01 1.600e+01 3.400e+01 2.700e+01 3.200e+01 3.400e+01 3.300e+01 3.300e+01
 8.200e+01 9.100e+01 3.300e+01 4.800e+01 4.000e+01 9.900e+01 7.900e+01 5.000e+01 4.900e+01 1.070e+02 6.700e+01 6.200e+01 6.100e+01
 9.300e+01 6.400e+01 8.300e+01 1.210e+02 1.010e+02 7.900e+01 8.800e+01 7.300e+01 8.900e+01 1.330e+02 1.350e+02 3.797e+03 9.780e+02
 1.610e+02 9.800e+01 3.805e+03 1.350e+02 7.130e+02 4.140e+02 1.170e+02 3.815e+03 9.700e+01 2.940e+02 1.160e+02 3.823e+03 1.530e+02
 1.870e+02 2.770e+02 1.140e+02 2.560e+02 1.390e+02 3.837e+03 1.990e+02 3.160e+02 3.843e+03 1.645e+03 1.900e+02 1.530e+02 3.851e+03
 6.610e+02 1.350e+02 1.400e+02 1.630e+02 4.236e+03 3.863e+03 8.730e+02 2.900e+02 2.920e+02 3.871e+03 3.210e+02 2.350e+02 3.250e+02
 5.190e+02 7.850e+02 3.883e+03 6.930e+02 1.910e+02 4.920e+02 1.950e+02 3.893e+03 1.695e+03 2.400e+02 2.030e+02 3.901e+03 1.860e+02
 4.090e+02 5.100e+02 4.130e+02 2.390e+02 4.170e+02 6.780e+02 2.210e+02 5.590e+02 3.

In [23]:
top_secret5 = top_secret4.reshape(-1,5)
print(top_secret5)
print(type(top_secret5))
top_secret_evens = np.arange(2,383,2)
#print(top_secret5)
#print(top_secret_evens)



[[5.900e+01 5.000e+01 2.900e+01 9.000e+00 2.900e+01]
 [7.300e+01 1.600e+01 3.400e+01 2.700e+01 3.200e+01]
 [3.400e+01 3.300e+01 3.300e+01 8.200e+01 9.100e+01]
 [3.300e+01 4.800e+01 4.000e+01 9.900e+01 7.900e+01]
 [5.000e+01 4.900e+01 1.070e+02 6.700e+01 6.200e+01]
 [6.100e+01 9.300e+01 6.400e+01 8.300e+01 1.210e+02]
 [1.010e+02 7.900e+01 8.800e+01 7.300e+01 8.900e+01]
 [1.330e+02 1.350e+02 3.797e+03 9.780e+02 1.610e+02]
 [9.800e+01 3.805e+03 1.350e+02 7.130e+02 4.140e+02]
 [1.170e+02 3.815e+03 9.700e+01 2.940e+02 1.160e+02]
 [3.823e+03 1.530e+02 1.870e+02 2.770e+02 1.140e+02]
 [2.560e+02 1.390e+02 3.837e+03 1.990e+02 3.160e+02]
 [3.843e+03 1.645e+03 1.900e+02 1.530e+02 3.851e+03]
 [6.610e+02 1.350e+02 1.400e+02 1.630e+02 4.236e+03]
 [3.863e+03 8.730e+02 2.900e+02 2.920e+02 3.871e+03]
 [3.210e+02 2.350e+02 3.250e+02 5.190e+02 7.850e+02]
 [3.883e+03 6.930e+02 1.910e+02 4.920e+02 1.950e+02]
 [3.893e+03 1.695e+03 2.400e+02 2.030e+02 3.901e+03]
 [1.860e+02 4.090e+02 5.100e+02 4.130e+02 2.39

In [19]:
top_secret5[:,0] = top_secret5[:,0]-top_secret_evens
print(top_secret5)
print(top_secret5.shape)
print(top_secret_evens.shape)

[[ 5.700e+01  5.000e+01  2.900e+01  9.000e+00  2.900e+01]
 [ 6.900e+01  1.600e+01  3.400e+01  2.700e+01  3.200e+01]
 [ 2.800e+01  3.300e+01  3.300e+01  8.200e+01  9.100e+01]
 [ 2.500e+01  4.800e+01  4.000e+01  9.900e+01  7.900e+01]
 [ 4.000e+01  4.900e+01  1.070e+02  6.700e+01  6.200e+01]
 [ 4.900e+01  9.300e+01  6.400e+01  8.300e+01  1.210e+02]
 [ 8.700e+01  7.900e+01  8.800e+01  7.300e+01  8.900e+01]
 [ 1.170e+02  1.350e+02  3.797e+03  9.780e+02  1.610e+02]
 [ 8.000e+01  3.805e+03  1.350e+02  7.130e+02  4.140e+02]
 [ 9.700e+01  3.815e+03  9.700e+01  2.940e+02  1.160e+02]
 [ 3.801e+03  1.530e+02  1.870e+02  2.770e+02  1.140e+02]
 [ 2.320e+02  1.390e+02  3.837e+03  1.990e+02  3.160e+02]
 [ 3.817e+03  1.645e+03  1.900e+02  1.530e+02  3.851e+03]
 [ 6.330e+02  1.350e+02  1.400e+02  1.630e+02  4.236e+03]
 [ 3.833e+03  8.730e+02  2.900e+02  2.920e+02  3.871e+03]
 [ 2.890e+02  2.350e+02  3.250e+02  5.190e+02  7.850e+02]
 [ 3.849e+03  6.930e+02  1.910e+02  4.920e+02  1.950e+02]
 [ 3.857e+03  

In [20]:


top_secret5[17:24,2] = top_secret5[17:24,2] - 100
print(top_secret5)

[[ 5.700e+01  5.000e+01  2.900e+01  9.000e+00  2.900e+01]
 [ 6.900e+01  1.600e+01  3.400e+01  2.700e+01  3.200e+01]
 [ 2.800e+01  3.300e+01  3.300e+01  8.200e+01  9.100e+01]
 [ 2.500e+01  4.800e+01  4.000e+01  9.900e+01  7.900e+01]
 [ 4.000e+01  4.900e+01  1.070e+02  6.700e+01  6.200e+01]
 [ 4.900e+01  9.300e+01  6.400e+01  8.300e+01  1.210e+02]
 [ 8.700e+01  7.900e+01  8.800e+01  7.300e+01  8.900e+01]
 [ 1.170e+02  1.350e+02  3.797e+03  9.780e+02  1.610e+02]
 [ 8.000e+01  3.805e+03  1.350e+02  7.130e+02  4.140e+02]
 [ 9.700e+01  3.815e+03  9.700e+01  2.940e+02  1.160e+02]
 [ 3.801e+03  1.530e+02  1.870e+02  2.770e+02  1.140e+02]
 [ 2.320e+02  1.390e+02  3.837e+03  1.990e+02  3.160e+02]
 [ 3.817e+03  1.645e+03  1.900e+02  1.530e+02  3.851e+03]
 [ 6.330e+02  1.350e+02  1.400e+02  1.630e+02  4.236e+03]
 [ 3.833e+03  8.730e+02  2.900e+02  2.920e+02  3.871e+03]
 [ 2.890e+02  2.350e+02  3.250e+02  5.190e+02  7.850e+02]
 [ 3.849e+03  6.930e+02  1.910e+02  4.920e+02  1.950e+02]
 [ 3.857e+03  

In [21]:
top_secret5[:,3] =  top_secret5[:,3] *2
top_secret5[:,4] = top_secret5[:,4] *2
print(top_secret5)

[[ 5.700e+01  5.000e+01  2.900e+01  1.800e+01  5.800e+01]
 [ 6.900e+01  1.600e+01  3.400e+01  5.400e+01  6.400e+01]
 [ 2.800e+01  3.300e+01  3.300e+01  1.640e+02  1.820e+02]
 [ 2.500e+01  4.800e+01  4.000e+01  1.980e+02  1.580e+02]
 [ 4.000e+01  4.900e+01  1.070e+02  1.340e+02  1.240e+02]
 [ 4.900e+01  9.300e+01  6.400e+01  1.660e+02  2.420e+02]
 [ 8.700e+01  7.900e+01  8.800e+01  1.460e+02  1.780e+02]
 [ 1.170e+02  1.350e+02  3.797e+03  1.956e+03  3.220e+02]
 [ 8.000e+01  3.805e+03  1.350e+02  1.426e+03  8.280e+02]
 [ 9.700e+01  3.815e+03  9.700e+01  5.880e+02  2.320e+02]
 [ 3.801e+03  1.530e+02  1.870e+02  5.540e+02  2.280e+02]
 [ 2.320e+02  1.390e+02  3.837e+03  3.980e+02  6.320e+02]
 [ 3.817e+03  1.645e+03  1.900e+02  3.060e+02  7.702e+03]
 [ 6.330e+02  1.350e+02  1.400e+02  3.260e+02  8.472e+03]
 [ 3.833e+03  8.730e+02  2.900e+02  5.840e+02  7.742e+03]
 [ 2.890e+02  2.350e+02  3.250e+02  1.038e+03  1.570e+03]
 [ 3.849e+03  6.930e+02  1.910e+02  9.840e+02  3.900e+02]
 [ 3.857e+03  

In [ ]:
top_secret6 = top_secret5.flatten()
print(top_secret6)

In [160]:
print(np.all(top_secret6[500:]<100))
print(np.sum(top_secret6[500:]<100))
print(np.all(top_secret6[37:464]>=0))

False
451
False
False
451
False


In [129]:

top_secret6[37:464] = np.sqrt(top_secret6[37:464])

<positron-console-cell-129>:1: RuntimeWarning: invalid value encountered in sqrt


In [ ]:
top_secret7 = np.round(top_secret6)

In [ ]:
top_secret7[top_secret7==39]=20

In [ ]:
print(np.sum(top_secret7 % 2 ==0))